import type { ItemizationFormData } from "../types";

export const AIRTABLE_FIELD_MAP: Partial<Record<keyof ItemizationFormData, string>> = {
  brandPartner: "Brand Partner",
  seller: "Seller",
  newSellerId: "Seller ID (new seller)",
  inventoryFile: "Inventory File",
  additionalFiles: "Additional Files",
  inventoryType: "Inventory Type",
  productAssortment: "Product Assortment",
  inventoryCondition: "Inventory Condition",
  overallListingRating: "Overall Listing Rating",
  pricingStrengthSurplus: "SP Pricing",
  pricingStrengthWholesale: "WH Pricing",
  brandDemandSurplus: "SP Brand Demand",
  brandDemandWholesale: "WH Brand Demand",
  locationSurplus: "SP Location",
  locationWholesale: "WH Location",
  restrictionsSurplus: "SP Restrictions",
  restrictionsWholesale: "WH Restrictions",
  categoryGroups: "Category Groups",
  inventoryExclusivity: "Inventory Exclusivity",
  paperwork: "Paperwork",
  tagPresets: "Tag presets",
  allTags: "All tags",
  inventoryNotes: "Notes",
  region: "Region",
  state: "State",
  city: "City",
  minimumOrder: "Minimum Order",
  packagingType: "Packaging Type",
  packagingDetails: "Packaging Details",
  inventoryAvailability: "Inventory Availability",
  fobOrExw: "FOB or EXW?",
  leadTimeNumber: "Lead Time Number",
  leadTimeInterval: "Lead Time Interval",
  itemizationType: "Itemization Type",
  currencyType: "Currency Type",
  inlandFreight: "Does this lot incur inland freight?",
  marginTakeRate: "Margin % (Take Rate)",
  priceColumns: "Price Columns",
  sellerPriceColumn: "Seller Price Column",
  buyerPriceColumn: "Buyer Price Column",
  flatOrReference: "Flat Item Price or Reference?",
  referencePriceColumn: "Reference Price Column",
  increaseOrDecrease: "Increase or decrease?",
  maxPercentOffAsking: "Max Percent Off Asking",
  listingDisaggregation: "Listing disaggregation",
  customDisaggregation: "Custom disaggregation",
  stealth: "Stealth?",
  restrictionsString: "Restrictions (string)",
  restrictionsCompany: "Restrictions (Company)",
  restrictionsBuyerType: "Restrictions (Buyer Type)",
  restrictionsRegion: "Restrictions (Region)",
  p0FireListing: "P0 Fire Listing?",
  notes: "Notes",
};
