import type { ItemizationFormData } from "../types";

export const AIRTABLE_FIELD_MAP: Partial<Record<keyof ItemizationFormData, string>> = {
  brandPartner: "Brand Partner",
  seller: "Seller",
  newSellerId: "Seller ID (new seller)",
  inventoryFile: "Inventory File",
  additionalFiles: "Additional Files",
  inventoryType: "Inventory Type",
  productAssortment: "Assortment Strength",
  inventoryCondition: "Inventory Quality",
  overallListingRating: "Overall Rating",
  pricingStrengthSurplus: "SP Pricing",
  pricingStrengthWholesale: "WH Pricing",
  brandDemandSurplus: "SP Brand Demand",
  brandDemandWholesale: "SP Brand Demand",
  locationSurplus: "SP US Landed",
  locationWholesale: "WH US Landed",
  restrictionsSurplus: "SP Restrictions",
  restrictionsWholesale: "SP Restrictions",
  categoryGroups: "Category Groups",
  inventoryExclusivity: "Exclusivity",
  paperwork: "Paperwork",
  tagPresets: "Tag Presets",
  allTags: "Tags",
  inventoryNotes: "Notes",
  region: "Region",
  state: "State",
  city: "City (string)",
  minimumOrder: "Minimum Order (String)",
  packagingType: "Packaging Type",
  packagingDetails: "Packaging Details",
  inventoryAvailability: "Inventory Availability",
  fobOrExw: "FOB or EXW?",
  leadTimeNumber: "Lead Time",
  leadTimeInterval: "Lead Time Interval",
  itemizationType: "Itemization Type",
  currencyType: "Currency Type",
  inlandFreight: "Lot Inland Freight",
  marginTakeRate: "Margin (Take Rate)",
  priceColumns: "Price Columns",
  sellerPriceColumn: "Seller Price Column",
  buyerPriceColumn: "Buyer Price Column",
  flatOrReference: "Flat Item Price or Reference?",
  referencePriceColumn: "Reference Price Column",
  increaseOrDecrease: "Reference Column Calculation",
  maxPercentOffAsking: "Minimum Acceptable Offer",
  listingDisaggregation: "Listing Disaggregation Options",
  customDisaggregation: "Listing Disaggregation Notes",
  stealth: "Stealth",
  restrictionsString: "Restrictions (string)",
  restrictionsCompany: "Restrictions (Company)",
  restrictionsBuyerType: "Restrictions (Buyer Type)",
  restrictionsRegion: "Restrictions (Region)",
  p0FireListing: "WH - P0 Fire Listing",
  notes: "Notes",
};
